### PR TITLE
Player.cs & Server.cs changes

### LINKED ISSUE #151: NRE with player.SendBroadcast method
```
[2023-01-10 21:43:39.457 +01:00] [STDOUT] NullReferenceException
[2023-01-10 21:43:39.457 +01:00] [STDOUT]   at (wrapper managed-to-native) UnityEngine.Component.get_gameObject(UnityEngine.Component)
[2023-01-10 21:43:39.457 +01:00] [STDOUT]   at PluginAPI.Core.Player.get_GameObject () [0x00006] in <4c2a3c9f04a54612acd3e9a88faf0eba>:0
[2023-01-10 21:43:39.457 +01:00] [STDOUT]   at PluginAPI.Core.Player.TryGetComponent[T] (T& component, System.Boolean globalSearch) [0x00069] in <4c2a3c9f04a54612acd3e9a88faf0eba>:0
[2023-01-10 21:43:39.457 +01:00] [STDOUT]   at PluginAPI.Core.Player.GetComponent[T] (System.Boolean globalSearch) [0x00000] in <4c2a3c9f04a54612acd3e9a88faf0eba>:0
[2023-01-10 21:43:39.457 +01:00] [STDOUT]   at PluginAPI.Core.Player.SendBroadcast (System.String message, System.UInt16 duration, Broadcast+BroadcastFlags type, System.Boolean shouldClearPrevious) [0x0000f] in <4c2a3c9f04a54612acd3e9a88faf0eba>:0
[2023-01-10 21:43:39.457 +01:00] [STDOUT]   at Empire.PlayerMonitor+<CheckPlayers>d__3.MoveNext () [0x005a5] in <2da5aec10dc0489b9e1c653e6b748fd8>:0
[2023-01-10 21:43:39.457 +01:00] [STDOUT]   at MEC.Timing.Update () [0x0043c] in <e69551d3fc7c409c85358bb7b4e8ecc3>:0
[2023-01-10 21:43:39.457 +01:00] [STDOUT] UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
[2023-01-10 21:43:39.457 +01:00] [STDOUT] UnityEngine.DebugLogHandler:LogException(Exception, Object)
[2023-01-10 21:43:39.457 +01:00] [STDOUT] UnityEngine.Logger:LogException(Exception, Object)
[2023-01-10 21:43:39.457 +01:00] [STDOUT] UnityEngine.Debug:LogException(Exception)
[2023-01-10 21:43:39.457 +01:00] [STDOUT] MEC.Timing:Update()
[2023-01-10 21:43:39.457 +01:00] [STDOUT] (Filename: <4c2a3c9f04a54612acd3e9a88faf0eba> Line: 0)
```

NRE happens very often with player.SendBroadcast method, even if the player is not null, ready, in game, alive, etc..

### LINKED ISSUE #152: FacilityRoom.Lights is always null
FlickerableLightController is a Child component

```cs
public FacilityRoom(FacilityZone zone, RoomIdentifier room)
		{
			Zone = zone;
			Identifier = room;

			if (room.TryGetComponent(out FlickerableLightController lightController))
				Lights = new RoomLight(lightController);

			Facility.RegisterDoors(this, room.gameObject.GetComponentsInChildren<DoorVariant>());
		}
```

### PR DESCRIPTION
**Pull request by SrLicht**
# Server.cs
* Added ``int PlayerCount => Player.Count;``
* Added ``PermissionsHandler PermissionsHandler => ServerStatic.GetPermissionsHandler();``
* Added ``double TPS => Math.Round(1f / Time.smoothDeltaTime);``
* Added  get or set ``float SpawnProtectDuration``
* Added get or set ``bool IsHeavilyModded``
* Added ``Broadcast Broadcast => Broadcast.Singleton``

# Player.cs
* Added ``PlayerRoleBase RoleBase => ReferenceHub.roleManager.CurrentRole;``
* Added ``Dictionary<ItemType, ushort> AmmoBag => ReferenceHub.inventory.UserInventory.ReserveAmmo;``
* Added get or set ``string RoleColor`` (serverRoles)
* Added get or set ``string RoleName``
* Added ``string UnitName => ReferenceHub.roleManager.CurrentRole is HumanRole humanRole ? humanRole.UnitName : null;``
* Added ``bool HasReservedSlot => ReservedSlot.HasReservedSlot(UserId, out _);``
* Added ``Vector3 Velocity => ReferenceHub.GetVelocity();``
* Added ``VoiceModuleBase VoiceModule => ReferenceHub.roleManager.CurrentRole is IVoiceRole voiceRole ? voiceRole.VoiceModule : null;`` Can be null
* Added ``VoiceChatChannel VoiceChannel => VoiceModule?.CurrentChannel ?? VoiceChatChannel.None;``
* Change ``bool IsScp => Role.GetTeam() is Team.SCPs;``
* Added ``bool IsNTF => Role.GetTeam() is Team.FoundationForces;``
* Added ``bool IsCHI => Role.GetTeam() is Team.ChaosInsurgency;``
* Added ``bool IsTutorial => Role is RoleTypeId.Tutorial;``
* Added ``SetGroup(UserGroup group) ReferenceHub.serverRoles.SetGroup(group, false);``

# Fixes
* Fixed a bug where FacilityRooms.Light was always null  fix #152 
* Fixed a bug that caused SendBroadcast to occasionally throw NRE errors  fix #151

### CODE REVIEW

File: NwPluginAPI/Core/Player.cs [hunk 1]
```diff
@@ -916,6 +1002,36 @@ public void SendBroadcast(string message, ushort duration, BroadcastFlags type =
 			Server.Instance.GetComponent<Broadcast>().TargetAddElement(ReferenceHub.characterClassManager.connectionToClient, message, duration, type);
 		}
 
+		/// <summary>
+		/// Sets the player server role. why group is private....
+		/// </summary>
+		/// <param name="name">Name of server role to set.</param>
+		/// <param name="group">Group to be set.</param>
+		public void SetServerRole(string name, UserGroup group)
```
Comment (zabszk) [inline NwPluginAPI/Core/Player.cs:1010]: What's a possible use-case for this? This only updates the user groups cache, so the changes are temporary (will be removed on round restart, config reload) and won't even update the player role (if the player is already on the server it won't update their role).

Comment (SrLicht) [reply NwPluginAPI/Core/Player.cs:1010]: I know, I wasn't looking for a permanent one, if I wanted a permanent one I would make it write to a file, I was thinking more about using it in a DB that would check every time a player enters and give him the role and when the round is over he reconnects to the server so it would re-run the event.

Comment (SrLicht) [reply NwPluginAPI/Core/Player.cs:1010]: I use this method for the VIPs of my server, when a player enters I check if he is in the DB cache, I see what group he is in (vip, vip+ etc) and if he has not yet expired.

```cs
 public async void CheckForVIPAsync(Player player)
        {
            var role = TempRoleAPI.GetGroup(player.UserId);

            if (role != null)
            {
                if (ServerStatic.GetPermissionsHandler()._groups.ContainsKey(role))
                {
                    var group = ServerStatic.GetPermissionsHandler()._groups[role];

                    player.SetRank(group.BadgeText, group);
                }
                else
                {
                    Log.Error($"UserGroup {role} dont exist");
                }
            }
        }
```

Comment (zabszk) [reply NwPluginAPI/Core/Player.cs:1010]: I think that an event that can override getting role/group will be better.

Comment (SrLicht) [reply NwPluginAPI/Core/Player.cs:1010]: Curiously I had already made a branch with new events and I wanted to add PlayerChangingGroup, but I have no idea if ServerRoles.SetGroup is executed every time someone connects or only when they have a UserGroup.
https://github.com/SrLicht/NwPluginAPI/commit/aafd758d00452b0a1aa5d2f84c85698cce4715ab#

File: NwPluginAPI/Core/Server.cs [hunk 2]
```diff
@@ -83,6 +92,48 @@ public static int ReservedSlots
...
+		public static bool IsHeavilyModded
+		{
+			get => CustomNetworkManager.HeavilyModded;
+			set => CustomNetworkManager.HeavilyModded = value;
+		}
+
+		/// <summary>
+		/// Get or set server has whitelist enabled.
+		/// </summary>
+		public static bool IsWhitelisted
```
Comment (zabszk) [inline NwPluginAPI/Core/Server.cs:131]: This can be confusing, because it doesn't control whether whitelist is enabled. It only controls whether server should report itself as using ANY whitelisting solution to the Central Servers.

**Comment by moddedmcplayer** [comment]
Server.cs:
Tps should be all caps, not sure what frames is supposed to do.
Spawn protected time -> spawn protection time.
If you think people are happy with PlayersConnected, keep it. Just I think first though that comes to your head when getting player count would be playercount or players.

**Comment by moddedmcplayer** [comment]
Player:
Ammo -> ReserveAmmo, ammo makes it sound like it also contains gun ammo.
UnitName and VoiceChannel if voicemodule can be null, why cant this be too? I would prefer doing UnitName ?? "No Unit" instead of UnitName == string.Empty ? "" : "".
IsScp all caps

IsCHI IsTutorial - gotta keep it consistent, either do IsCHI and IsTUT or do IsChaos and IsTutorial

**Comment by SrLicht** [comment]
> Player: Ammo -> ReserveAmmo, ammo makes it sound like it also contains gun ammo. UnitName and VoiceChannel if voicemodule can be null, why cant this be too? I would prefer doing UnitName ?? "No Unit" instead of UnitName == string.Empty ? "" : "". IsScp all caps
> 
> IsCHI IsTutorial - gotta keep it consistent, either do IsCHI and IsTUT or do IsChaos and IsTutorial

VoiceChannel  it's an enum so it can't be null

File: NwPluginAPI/Core/Server.cs (hunk 2 above)
Comment (SrLicht) [reply NwPluginAPI/Core/Server.cs]: ok i will remove it

**Comment by moddedmcplayer** [comment]
> > Player: Ammo -> ReserveAmmo, ammo makes it sound like it also contains gun ammo. UnitName and VoiceChannel if voicemodule can be null, why cant this be too? I would prefer doing UnitName ?? "No Unit" instead of UnitName == string.Empty ? "" : "". IsScp all caps
> > IsCHI IsTutorial - gotta keep it consistent, either do IsCHI and IsTUT or do IsChaos and IsTutorial
> 
> VoiceChannel it's an enum so it can't be null

then wtf is `VoiceChannel => VoiceModule?.CurrentChannel ?? VoiceChatChannel.None` supposed to do

**Comment by SrLicht** [comment]
if(player.VoiceChannel == VoiceChatChannel.Mimicry) Log.Info("SUS")

**Comment by moddedmcplayer** [comment]
Remove the ?? and mark it as nullable

**Comment by moddedmcplayer** [comment]
Goofy mf

**Comment by SebasCapo** [comment]
> Goofy mf

Consider keeping a respectful attitude towards fellow contributors please :)

**Comment by moddedmcplayer** [comment]
> > Goofy mf
> 
> Consider keeping a respectful attitude towards fellow contributors please :)

Goofy mf isn't an insult isn't it? If you feel offended I am sorry.

**Review by zabszk — APPROVED** [review]
